<!--breadcrumbs start-->
<div id="page-title" class="page-title page-title-1 bg-secondary dark">
    <div class="container">
        <div class="row">
            <div class="col-md-7">

            </div>
        </div>
    </div>
</div>
    <!--breadcrumbs end-->

<!--container start-->
    <div class="white-bg">

        <!-- career -->
    <div class="container career-inner">

        <hr>
        <div class="row">
            <div itemprop="articleBody">
		<div class="dbContent">
            <h1 class="text-center"><i class="ti-layout-menu"></i>Terms  and Condition</h1>
            <hr class="hr-class">
            <div class="col-md-12 career-head">
                <h5 class="wow fadeIn text-center">Welcome To ForAllDoctors.Com We truly thank you for your interest.</h5>

            </div>

<p class="MsoNormal" style="margin-bottom: 0.0001pt; text-align: center;"><strong><span style="font-size: 16.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">Welcome To ForAllDoctors.Com </span></strong></p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt; text-align: center;"><strong><span style="font-size: 16.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">We truly thank you for your interest.</span></strong></p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt; text-align: center;">&nbsp;</p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt; text-align: center;"><strong><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">PLEASE BE AWARE THAT BY APPLYING TO FORALLDOCTORS.COM, YOU GIVE US, WITHOUT LIMITATION, FULL AUTHORIZATION TO USE ANY SOURCE FOR VERIFICATION. PLEASE BE AWARE THAT ANYONE WHO REGISTERS WITH FORALLDOCTORS.COM UNDER FALSE PRETENSES OR FALSE IDENTITY, MAY BE SUBJECT TO PROSECUTION BY RELEVANT AUTHORITIES TO THE FULLEST EXTENT OF THE LAW.</span></strong></p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt; text-align: center;">&nbsp;</p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">Registrants and Members must read the Terms and Conditions of this Agreement in its entirety.&nbsp; By using or browsing the ForAllDoctors.com Site, You acknowledge that You have read, understood, and agreed to be unconditionally bound by the Terms and Conditions of this Agreement and all applicable laws and regulations.&nbsp; ForAllDoctors.com permits You to use its site(s) only in accordance with the Terms and Conditions of this Agreement.&nbsp; Upon acceptance, this Agreement including any of its subsequent amendments is enforceable against You.&nbsp; <strong><span style="text-decoration: underline;">If You Do Not Agree With The Terms and Conditions Of This Agreement, You Must Immediately Stop Using The ForAllDoctors.com Site. </span></strong>THIS IS NOT A MUTUALLY AGREED AGREEMENT AND DOES NOT CONFER ANY THIRD PARTY BENEFICIARY RIGHTS.</span></p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;">&nbsp;</p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt; text-align: center;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">YOU HEREBY CERTIFY AND AFFIRM THAT: </span></p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt; text-align: center;">&nbsp;</p>
<p class="MsoNormalCxSpMiddle" style="margin: 0cm 0cm 0.0001pt 36pt; text-indent: -18pt;"><!-- [if !supportLists]--><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">(1) </span><!--[endif]--><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">ALL INFORMATION, DOCUMENTATION &amp; CONTENT YOU HAVE GIVEN ON THIS REGISTRATION ARE TRUE, CURRENT, ACCURATE &amp; AUTHENTIC AND,</span></p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;">&nbsp;</p>
<p class="MsoNormalCxSpMiddle" style="margin: 0cm 0cm 0.0001pt 36pt; text-indent: -18pt;"><!-- [if !supportLists]--><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">(2) </span><!--[endif]--><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">YOU WILL MAKE SURE THAT ALL INFORMATION, DOCUMENTATION &amp; CONTENT YOU HAVE GIVEN WILL REMAIN TRUE, CURRENT, ACCURATE &amp; AUTHENTIC DURING YOUR MEMBERSHIP AND,</span></p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;">&nbsp;</p>
<p class="MsoNormalCxSpMiddle" style="margin: 0cm 0cm 0.0001pt 36pt; text-indent: -18pt;"><!-- [if !supportLists]--><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">(3) </span><!--[endif]--><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">YOU SIGN THIS AGREEMENT WITH THE FULL KNOWLEDGE THAT ANY FALSE, INACCURATE OR MISLEADING INFORMATION, DOCUMENTATION &amp; CONTENT YOU GIVE NOW OR DURING YOUR MEMBERSHIP, CAN CONSTITUTE FORGERY UNDER TITLE 18, CHAPTER 47, §&nbsp;1028 OF THE UNITED STATES LAWS AND, </span></p>
<p class="MsoNormalCxSpMiddle" style="margin-bottom: 0.0001pt;">&nbsp;</p>
<p class="MsoNormalCxSpMiddle" style="margin: 0cm 0cm 0.0001pt 36pt; text-indent: -18pt;"><!-- [if !supportLists]--><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">(4) </span><!--[endif]--><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">YOUR ELECTRONIC SIGNATURE SHALL HAVE THE SAME LEGAL EFFECT AS IF MADE UNDER OATH. </span></p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt; text-align: center;">&nbsp;</p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-bidi-font-weight: bold;" lang="EN-US">You acknowledge and agree that, if you have any objections to any of the terms and conditions attached to membership in or any use of the ForAllDoctors.com site, <span style="text-decoration: underline;">Your only recourse is to cease using ForAllDoctors.com site at once</span>.</span></p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt; text-align: center;">&nbsp;</p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">This is a PRIVATE Site, designated for its Members Only.&nbsp; ForAllDoctors.com reserves the right to refuse any prospective Member and/or invite any current Member to leave the Site, without cause or notice, at any time. </span></p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;">&nbsp;</p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;"><strong><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">ForAllDoctors.com reserves the right to make any changes, additions, deletions and/or modifications to the Terms and Conditions of this Agreement for any purpose,&nbsp; without any notice, at anytime, even after You have registered for Membership, so We suggest that You periodically visit this page to review these Terms and Conditions.&nbsp; By continuing to use the ForAllDoctors.com Site after We post any changes, You agree to accept all changes, additions, deletions and/or modifications to this Agreement, whether or not You actually read them.</span></strong><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US"> You may access and review the most current version of the Terms and Conditions of this Agreement from the link at the bottom of the ForAllDoctors.com Site home page.&nbsp; It Is Your Responsibility to read and understand the Terms and Conditions of this Agreement in its amended form, each time either before or upon signing in to access the ForAllDoctors.com Site. </span></p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;">&nbsp;</p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">Although You may find Our Site and Members exquisite to visit and participate in, as the philosopher Epicurus said, “Be moderate in order to taste the joys of life in abundance.”&nbsp; Therefore, we ask that you please use Our Site reasonably and responsibly and be aware that Your appreciation and enjoyment of Our Site does not habituate into dependence or an obsession.</span></p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;">&nbsp;</p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">You acknowledge, agree and consent that ForAllDoctors.com may, but is not obligated to, investigate Your use of the ForAllDoctors.com Site, to determine Your compliance with the Terms and Conditions of this Agreement and any of its amendments; and (including without limitation), in response to any subpoena, court order or any other legal process, any claims of violation of safety or property rights of any other individual or entity.&nbsp; You acknowledge and agree that in the event You are required to present Yourself to relevant authorities, You will at Your own expense, confirm Your identity and cooperate in the investigation.</span></p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;">&nbsp;</p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">Please know that although We are always glad to receive Your input, feedback, comments, ideas, contributions, or any other suggestions &amp; Content, We ask that You please not be discouraged if they are not utilized.&nbsp; All input, feedback, comments, ideas, contributions, or any other suggestions and Content, Communicated by You to Us or through the ForAllDoctors.com Site, will be treated as non-confidential and non-proprietary and may be disclosed, Communicated or used by ForAllDoctors.com or its site(s) for any purpose whatsoever, without any obligation to compensate You (just as You have no obligation to offer them). </span></p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;">&nbsp;</p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">We reserve the right and sole discretion to enforce or choose not to enforce any Terms and Conditions of this Agreement; however, Our inaction shall not be deemed a waiver of Our right to enforce any of the Terms and Conditions of this Agreement or take any actions against any Member or any other third party in the event of any breach hereunder or any future breach.</span></p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;">&nbsp;</p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;"><span style="text-decoration: underline;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">Please remember that Your Account information is password protected and You must keep Your password safe.&nbsp; You are solely responsible to keep Your password confidential.&nbsp; You acknowledge and agree that You will at all times be held accountable for all activities that occur under Your Member Account.&nbsp; In the event that You become aware of any unauthorized use of Your Account or password, You must immediately notify ForAllDoctors.com at “Contact Us” on ForAllDoctors.com.&nbsp; However, ForAllDoctors.com has no obligation to act in response to such notice within any set time and furthermore, regardless of such notice to ForAllDoctors.com, <strong>You</strong> shall remain responsible for any use of Your Account until Your Account is deactivated or suspended by ForAllDoctors.com.&nbsp; You acknowledge and agree that in the event that You lose, forget, misplace or are a victim of unauthorized use of Your password, ForAllDoctors.com is not liable to You or any other party, for the loss of any or all Content or Communications of Your Account upon the issuance of another password to You.</span></span></p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;">&nbsp;</p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">YOU AGREE TO DEFEND, INDEMNIFY AND HOLD FORALLDOCTORS.COM HARMLESS FROM ANY CRITICISM, LIABILITY, CLAIM, DEMAND, CAUSE OF ACTION, LOSS OR DAMAGE OF ANY KIND (INCLUDING BUT NOT LIMITED TO, SPECIAL, DIRECT, INDIRECT, COMPENSATORY, CONSEQUENTIAL, EXEMPLARY, PUNITIVE OR INCIDENTAL DAMAGES OR FOR, LOSS OF USE, DATA, PROGRAMS, REPUTATION, GOOD WILL, PROPERTY, INCOME, PROFITS, PROPRIETARY OR CONFIDENTIAL INFORMATION, PRIVACY AND/OR ANY OTHER TANGIBLE, INTANGIBLE OR PECUNIARY LOSS, BUSINESS INTERRUPTION, OR, DAMAGE OR INJURY TO PERSON OR PROPERTY, OR, FOR FAILURE TO MEET ANY DUTY INCLUDING OF GOOD FAITH OR REASONABLE CARE AND/OR NEGLIGENCE, HOWEVER CAUSED AND UNDER ANY THEORY OF LIABILITY, WHETHER IN LAW OR EQUITY), EXPENSES, ATTORNEYS FEES AND COSTS, WHETHER BY YOU OR A THIRD PARTY, DUE TO OR ARISING OUT OF YOUR BREACH OF THE TERMS AND CONDITIONS AND SPIRIT OF THIS AGREEMENT AND/OR DUE TO OR ARISING OUT OF YOUR COMMUNICATIONS, CONTENT, ACTIONS, USE OR MISUSE OF THE FORALLDOCTORS.COM SITE. IN NO EVENT SHALL FORALLDOCTORS.COM BE LIABLE TO YOU OR ANY THIRD PARTY FOR ANY CLAIM, DEMAND, CAUSE OF ACTION, LOSS OR DAMAGE OF ANY KIND (INCLUDING BUT NOT LIMITED TO, SPECIAL, DIRECT, INDIRECT, COMPENSATORY, CONSEQUENTIAL, EXEMPLARY, PUNITIVE OR INCIDENTAL DAMAGES OR FOR LOSS OF USE, DATA, PROGRAMS, REPUTATION, GOOD WILL, PROPERTY, INCOME, PROFITS, PROPRIETARY OR CONFIDENTIAL INFORMATION, PRIVACY AND/OR ANY OTHER TANGIBLE, INTANGIBLE OR PECUNIARY LOSS, BUSINESS INTERRUPTION, OR, DAMAGE OR INJURY TO PERSON OR PROPERTY, OR, FOR FAILURE TO MEET ANY DUTY INCLUDING OF GOOD FAITH OR REASONABLE CARE AND/OR NEGLIGENCE, HOWEVER CAUSED AND UNDER ANY THEORY OF LIABILITY, WHETHER IN LAW OR EQUITY), EXPENSES, ATTORNEYS FEES AND COSTS, ARISING OUT OF OR IN CONNECTION WITH THE FORALLDOCTORS.COM SITE, OR THIS AGREEMENT. Some jurisdictions do not authorize exclusion or limitation of certain warranties or conditions, incidental or consequential damages or liability for loss or injury due to negligence, breach of contract or breach of implied terms; in such event, THE LIABILITY OF FORALLDOCTORS.COM TO YOU OR ANY THIRD PARTIES IN ANY CIRCUMSTANCE IS LIMITED TO THE ACTUAL AMOUNT OF DIRECT DAMAGES, EVEN IF DIRECT DAMAGES DO NOT SATISFY A REMEDY.&nbsp; FORALLDOCTORS.COM RESERVES THE RIGHT TO ALL REMEDIES AVAILABLE AT LAW AND IN EQUITY FOR VIOLATIONS OF THIS AGREEMENT AND FOR YOUR EXPOSING FORALLDOCTORS.COM TO CRITICISM OR LIABILITY. </span></p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;"><strong><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">REGARDLESS OF ANY STATUTE OR LAW TO THE CONTRARY, ANY CLAIM OR DEMAND OR CAUSE OF ACTION AGAINST FORALLDOCTORS.COM BY ANY MEMBER OR ANY OTHER PARTY OR THIRD PARTY ARISING OUT OF OR RELATED TO THE USE OR MISUSE OF THE FORALLDOCTORS.COM SITE, OR UNDER THE TERMS AND CONDITIONS OF THIS AGREEMENT, MUST BE FILED WITHIN FIFTEEN (15) DAYS AFTER SUCH CLAIM, DEMAND OR CAUSE OF ACTION AROSE, OR BE FOREVER BARRED.</span></strong></p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;">&nbsp;</p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">ForAllDoctors.com may (but is not obligated to) transfer, process, delete or archive (even after deletion from the ForAllDoctors.com Site) either in the United States or outside of the United States, any or all Content, in any way and at any time Communicated by and between You, Us, or any third party, whether on, through or in connection with the ForAllDoctors.com Site. &nbsp;ForAllDoctors.com shall not in any way be responsible or liable to You or any third party, for the processing, transfer, deletion, retention, corruption, archiving or the failure to process, transfer, delete, retain, secure, or archive (even after deletion from the ForAllDoctors.com Site) any or all Content, in any way and at any time Communicated by You, Us, or any third party, whether on, through or in connection with the ForAllDoctors.com Site.&nbsp; Consequently, it is Your responsibility to retain (only for Your personal use as authorized in this Agreement and Agreed to by You by use of ForAllDoctors.com Site) all such Communicated Content on Your own without relying on ForAllDoctors.com or its site(s) to retain it for You.&nbsp; By using the ForAllDoctors.com Site, You consent to the transfer, process, archive, retention, deletion, lack of retention, and unintended corruption of any and all Content in any way Communicated by You or to You or associated with You.&nbsp; THE LIMITATIONS ON FORALLDOCTORS.COM’S LIABILITIES SHALL APPLY REGARDLESS OF WHETHER FORALLDOCTORS.COM WAS PREVIOUSLY ADVISED OF THE POSSIBILITY OF SUCH BREACH, DAMAGES OR LOSS, OR SHOULD HAVE BEEN AWARE OF THE POTENTIAL FOR SUCH BREACH, DAMAGES OR LOSS OF ANY TYPE.</span></p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;">&nbsp;</p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">PLEASE BE ADVISED AND NOTE THAT FORALLDOCTORS.COM DOES NOT WARRANT THE SECURITY, FUNCTIONALITY, TIMELINESS, ACCURACY, INTEGRITY, QUALITY, RELIABILITY OR AVAILABILITY OF ITS SITE(S), EITHER IN WHOLE OR IN PART.&nbsp; You acknowledge and agree that ForAllDoctors.com reserves the right to limit, suspend, modify or discontinue the Site at any time without notice and, ForAllDoctors.com shall not be liable to any Member or any third party for such limitation, suspension, modification, or discontinuation of the ForAllDoctors.com Site.&nbsp; You acknowledge and agree that You will at Your own expense, respond to and resolve inquiries and complaints from any other Member or third party, that is in any manner related to Your actions, Communications, Content, use or misuse of the ForAllDoctors.com Site, whether on, through or in connection with the Site.</span></p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;">&nbsp;</p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">IN THE EVENT THAT FORALLDOCTORS.COM IS BY LAW COMPELLED TO FURNISH ANY COMMUNICATION OR CONTENT, THAT IT MAY POSSESS AND CAN RETRIEVE WITHOUT UNDUE BURDEN, THE FOLLOWING CHARGES AND FEES MUST BE PAID BY YOU, OR ON YOUR BEHALF, OR BY THE REQUESTING PARTY OR ENTITY, <span style="text-decoration: underline;">AT THE TIME</span> EACH SERVICE IS REQUESTED:</span></p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;">&nbsp;</p>
<p class="MsoNormalCxSpMiddle" style="margin: 0cm 0cm 0.0001pt 72pt; text-indent: -18pt;"><!-- [if !supportLists]--><span style="font-size: 12.0pt; font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol;" lang="EN-US">· </span><!--[endif]--><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">A NONREFUNDABLE PROCESSING FEE OF TWO THOUSAND NINE HUNDRED AND FIFTY (US$2,950.00); AND </span></p>
<p class="MsoNormalCxSpMiddle" style="margin-bottom: 0.0001pt;">&nbsp;</p>
<p class="MsoNormalCxSpMiddle" style="margin: 0cm 0cm 0.0001pt 72pt; text-indent: -18pt;"><!-- [if !supportLists]--><span style="font-size: 12.0pt; font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol;" lang="EN-US">· </span><!--[endif]--><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">A NONREFUNDABLE RECORD SEARCH FEE OF NINE HUNDRED AND SEVENTY FIVE (US$975.00) PER HOUR, ASSESSED FOR EACH <span style="text-decoration: underline;">INDIVIDUAL</span> DOCUMENT, NAME, BUSINESS NAME, ALIAS, ADDRESS, OR ANY OTHER SEARCH TERM REQUEST SUBMITTED OR CONDUCTED (WHICHEVER IS HIGHER).&nbsp; PLEASE NOTE THAT A RECORD SEARCH REQUEST WILL BE DENIED AND <span style="text-decoration: underline;">NO REFUND ISSUED</span>, UNLESS EACH INDIVIDUAL SEARCH TERM REQUESTED IS SPECIFICALLY, UNAMBIGUOUSLY AND SEPARATELY STATED; AND</span></p>
<p class="MsoNormalCxSpMiddle" style="margin-bottom: 0.0001pt;">&nbsp;</p>
<p class="MsoNormalCxSpMiddle" style="margin: 0cm 0cm 0.0001pt 72pt; text-indent: -18pt;"><!-- [if !supportLists]--><span style="font-size: 12.0pt; font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol;" lang="EN-US">· </span><!--[endif]--><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">A NONREFUNDABLE ISSUANCE FEE OF EIGHT HUNDRED AND SEVENTY FIVE (US$875.00) PER EACH PAGE COPIED.&nbsp; ALL SEARCH RESULT CONTENT AND DOCUMENTS WILL BE UNDER THE OFFICIAL SEAL OF FORALLDOCTORS.COM AND WILL ONLY BE FURNISHED IN PAPER FORMAT AND IN NO OTHER FORMAT, UNDER ANY CIRCUMSTANCES. </span></p>
<p class="MsoNormalCxSpMiddle" style="margin-bottom: 0.0001pt;">&nbsp;</p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">All requests must be made in writing and mailed-in through the United States Postal Service with certified mail and return receipt requested.&nbsp; To ensure proper crediting of all fees, each fee must be paid separately and payment must be made by certified bank check made payable to <img src="/images/ccorp.png" alt="" height="13px">.&nbsp; Please mail-in all requests and their corresponding payments to the up-to-date address that will be provided to you upon your e-mailed request made through the “Contact Us” link on ForAllDoctors.com.&nbsp; Please note that fees are liable to change and/or further fees added at anytime. </span></p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;">&nbsp;</p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">ForAllDoctors.com’s Secure SSL Certificate helps industries like the Healthcare and banking and finance industry to meet the government regulations imposed on their sensitive online data. ForAllDoctors.com is HIPAA and Sarbanes-Oxley compliant.&nbsp; <span style="text-decoration: underline;">However, please note that this Certificate only applies to the Non-Mobile version of the website.</span> </span></p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;">&nbsp;</p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">We try to securely store, transfer, process, retain, archive or delete Your information, Content and Communications but We cannot guarantee complete security.&nbsp; The most secure method of maintaining Your information is by You NOT sharing them with others.&nbsp; So, please proceed with caution at all times and please do not Communicate any personal, private, privileged or confidential information or Content (such as, social security number, phone numbers, drivers license number, date of birth or health information) on the ForAllDoctors.com Site that You expect to keep private.&nbsp; Even if We remove Communication or Content from Our Site, copies of it may remain elsewhere and cannot be removed, once it has been shared with or Communicated to others.&nbsp; <strong>IN SHORT, WE CANNOT CONTROL CONTENT YOU COMMUNICATE, SO PLEASE DO NOT SUBMIT ANYTHING YOU DEEM PRIVATE, PRIVILEGED, CONFIDENTIAL OR PERSONAL.</strong></span></p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;">&nbsp;</p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-bidi-font-weight: bold;" lang="EN-US">In efforts to provide You with a useful and creative experience, ForAllDoctors.com may share Your information, Content, Communication or data with third parties we deem reasonably necessary to maintain, expand or improve the Site offered by and through ForAllDoctors.com.</span></p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;">&nbsp;</p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">ForAllDoctors.com may disclose information, Content or Communications about its Members or a third party to law enforcement personnel or others, if We are of good faith belief that such disclosure is reasonably warranted to satisfy any applicable law, statute, regulation, comply with a subpoena, court order or any other legal process or proceeding, or in an effort to detect, prevent, protect or address (as may be applicable), against matters including fraud, security, harm to the property or safety of its Members or any other person or entity, as well as, to enforce the Terms and Conditions of this Agreement. In the event You are required to present Yourself to relevant authorities, You agree to do so at Your own cost and expense.</span></p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;">&nbsp;</p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">The inclusion of ANY Content or Communication whatsoever on the ForAllDoctors.com Site, whether Communicated by or through a Member or any other party, third party, person or entity, shall in no way be construed and does not imply, that ForAllDoctors.com or its site(s) in any way promotes, endorses or takes any position one way or another, regarding the (including without limitation) opinions, ideas, Websites, Web pages, data, information, illustrations, photographs, texts, video clips, graphics, scripts, content, causes, products or services of any Member, party, third party, person or entity. ForAllDoctors.com does not accept responsibility for any Communication or Content in any form or format Communicated on, through or in connection with the ForAllDoctors.com Site by any Member, party, third party, person or entity.&nbsp; ForAllDoctors.com shall not be liable for any breach, loss or damage of any kind incurred as a result of any reliance by You or any third party on the completeness, accuracy or continued availability of any of the above mentioned communication or content, that may in any manner be visible or communicated on, through or in connection with the ForAllDoctors.com Site by any Member, party, third party, person or entity,</span></p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;">&nbsp;</p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">For Your convenience, ForAllDoctors.com Site may Communicate Content, (including but not limited to) advertisements, links, hyperlinks, pop-ups, banner advertisements, websites, web pages, v-card, entities, persons, e-mails, addresses, locations, contacts to any other third party, entity or location.&nbsp; However, any and all such Content Communications, including but not limited to, advertisements, links, hyperlinks, pop-ups, banner advertisements, websites, web pages, v-card, entities, persons, e-mails, addresses, locations, contacts to any other third party, entity or <strong>may have privacy practices that differ from the ForAllDoctors.com Site; We are not responsible for and have no control over their Terms, Conditions of use, practices and privacy policies.&nbsp; We encourage all Members and other parties to read and understand the Terms, Conditions of use, practices and privacy policies of the advertisements, links, hyperlinks, pop-ups, banner advertisements, websites, web pages, v-card, entities, persons, e-mails, addresses, locations, contacts to any other third party, entity or locations they visit or Communicate with.</strong></span></p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;">&nbsp;</p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">ANY DEALINGS BETWEEN YOU AND ANY MEMBER OR THIRD PARTY WHETHER FOR PURCHASE, DELIVERY, PAYMENT, TERMS, CONDITIONS, WARRANTIES, REPRESENTATIONS OR ANYTHING ELSE, IS AT YOUR OWN RISK AND SOLELY BETWEEN YOU AND SAID MEMBER OR THIRD PARTY.&nbsp; <strong>(NOTE: Be sure to comply with all export licensing regulations, as export restrictions vary from country to country and item to item.&nbsp; For more information, please go to: </strong><a href="http://www.bis.doc.gov/exportliceningqanda.htm"><strong><span style="color: blue;">http://www.bis.doc.gov/exportliceningqanda.htm</span></strong></a><strong>.&nbsp; For compliance with any and all laws and regulations, You should consult the advice of a competent attorney or other relevant professional).</strong> You acknowledge and agree that ForAllDoctors.com shall <strong>not</strong> have any role, responsibility, or involvement in any transaction or communication between You and any Advertiser, other Member, non-member authorized user, or any third party, and does <strong>not</strong> (including without limitation) handle payments, guarantee transactions, provide escrow services, offer buyer protection, offer seller certification or, pay any taxes or other charges that may be directly or indirectly imposed by international, national, state or local laws and regulations. </span></p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">YOU ARE RESPONSIBLE TO TAKE ALL REASONABLE MEASURES TO AVOID, REDUCE, LIMIT AND MITIGATE ANY CLAIM, DEMAND, CAUSE OF ACTION, LOSS OR DAMAGE OF ANY KIND (INCLUDING BUT NOT LIMITED TO, SPECIAL, DIRECT, INDIRECT, COMPENSATORY, CONSEQUENTIAL, EXEMPLARY, PUNITIVE OR INCIDENTAL DAMAGES OR FOR LOSS OF USE, DATA, PROGRAMS, REPUTATION, GOOD WILL, PROPERTY, INCOME, PROFITS, PROPRIETARY OR CONFIDENTIAL INFORMATION, PRIVACY AND/OR ANY OTHER TANGIBLE, INTANGIBLE OR PECUNIARY LOSS, BUSINESS INTERRUPTION, OR, DAMAGE OR INJURY TO PERSON OR PROPERTY, OR, FOR FAILURE TO MEET ANY DUTY INCLUDING OF GOOD FAITH OR REASONABLE CARE AND/OR NEGLIGENCE, HOWEVER CAUSED AND UNDER ANY THEORY OF LIABILITY, WHETHER IN LAW OR EQUITY), EXPENSES, ATTORNEYS FEES AND COSTS YOU MAY INCUR AS A RESULT OF YOUR DEALINGS WITH ANY MEMBER OR ANY OTHER THIRD PARTY. IN THE EVENT OF ANY DISAGREEMENT, DISPUTE OR ANY OTHER MISCOMMUNICATION BETWEEN YOU AND ANY MEMBER OR THIRD PARTY, YOU ACKNOWLEDGE AND AGREE THAT FORALLDOCTORS.COM, SHALL HAVE NO OBLIGATION TO BECOME ENGAGED IN OR IN ANY WAY INTERVENE. </span></p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;">&nbsp;</p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">By registering for Membership with, subscribing to and/or participating in the ForAllDoctors.com Site, You are agreeing to abide by the Terms and Conditions of this Agreement.&nbsp; Failure to comply with the Terms and Conditions of this Agreement may result in the immediate elimination of the offending Member’s Membership and Account with, participation in, as well as any further access to, the ForAllDoctors.com Site, Content and/or Communications.&nbsp; Membership and Participation in ForAllDoctors.com Site is a privilege and not guaranteed in any manner. </span></p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">FORALLDOCTORS.COM RESERVES THE RIGHT TO IMMEDIATELY AND WITHOUT CAUSE, NOTICE AND/OR ANY FURTHER ACCESS, SUSPEND, DEACTIVATE, TERMINATE, REMOVE, LIMIT AND/OR BLOCK YOUR MEMBERSHIP, ACCOUNT, CONTENT, COMMUNICATIONS, AND/OR PARTICIPATION IN, USE OF OR ACCESS TO THE SITE IN WHOLE OR IN PART.&nbsp; FORALLDOCTORS.COM MAY AT ANY TIME, BLOCK YOUR IP ADDRESS (INCLUDING WITHOUT LIMITATION), REMOVE &amp; DISCARD ANY AND ALL OF YOUR ACCOUNT, MEMBERSHIP, INFORMATION, CONTENT AND COMMUNICATIONS IN ANY WAY RELATING TO YOU, FROM OUR SITE, WITHOUT ANY CAUSE, NOTICE AND/OR ANY FURTHER ACCESS BY YOU.&nbsp; FORALLDOCTORS.COM DOES NOT WARRANT THAT AFTER WE DEACTIVATE, SUSPEND, TERMINATE, REMOVE, LIMIT AND/OR BLOCK YOUR MEMBERSHIP, ACCOUNT, CONTENT, COMMUNICATIONS, AND/OR PARTICIPATION IN, USE OF OR ACCESS TO THE SITE, WHETHER ANY OR ALL (ORIGINAL OR DUPLICATES) OF YOUR CONTENT AND INFORMATION, IN ANY MANNER COMMUNICATED ON OR THROUGH OR IN CONNECTION WITH THE SITE WILL BE RETAINED OR NOT REMAIN IN ANY FORM OR LOCATION BY FORALLDOCTORS.COM OR ITS SITE(S) OR ANY OF ITS MEMBERS OR ANY THIRD PARTY.</span></p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;">&nbsp;</p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">FORALLDOCTORS.COM MAY ALSO ENGAGE LEGAL ACTION AGAINST YOU AND YOU AGREE TO INDEMNIFY AND HOLD FORALLDOCTORS.COM HARMLESS FROM ANY LIABILITY, CLAIM, DEMAND, CAUSE OF ACTION, LOSS OR DAMAGE OF ANY KIND (INCLUDING BUT NOT LIMITED TO, SPECIAL, DIRECT, INDIRECT, COMPENSATORY, CONSEQUENTIAL, EXEMPLARY, PUNITIVE OR INCIDENTAL DAMAGES OR FOR LOSS OF USE, DATA, PROGRAMS, REPUTATION, GOOD WILL, PROPERTY, INCOME, PROFITS, PROPRIETARY OR CONFIDENTIAL INFORMATION, PRIVACY AND/OR ANY OTHER TANGIBLE, INTANGIBLE OR PECUNIARY LOSS, BUSINESS INTERRUPTION, OR, DAMAGE OR INJURY TO PERSON OR PROPERTY, OR, FOR FAILURE TO MEET ANY DUTY INCLUDING OF GOOD FAITH OR REASONABLE CARE AND/OR NEGLIGENCE, HOWEVER CAUSED AND UNDER ANY THEORY OF LIABILITY, WHETHER IN LAW OR EQUITY), EXPENSES, ATTORNEYS FEES AND COSTS, FOR ANY HARM CAUSED TO FORALLDOCTORS.COM, ITS SITE(S), ITS MEMBERS OR ANY OTHER PARTY, AS A RESULT OF YOUR FAILURE TO COMPLY WITH THE TERMS AND CONDITIONS OF THIS AGREEMENT, AND (INCLUDING WITHOUT LIMITATION) YOUR CONDUCT, ACTIONS, FAILURE TO ACT, COMMUNICATIONS AND CONTENT,&nbsp; WHETHER ON, THROUGH OR IN CONNECTION WITH OUR SITE. WE MAY (BUT HAVE NO OBLIGATION TO) CONTACT OR INFORM OTHER MEMBERS OR ANY OTHER PARTY OR ENTITY, OF ANY OR ALL OF YOUR CONDUCT, BREACH, ACTIONS, FAILURE TO ACT AND/OR COMMUNICATIONS &amp; CONTENT, WHETHER ON, THROUGH OR IN CONNECTION WITH OUR SITE.&nbsp; Some jurisdictions do not authorize exclusion or limitation of certain warranties or conditions, incidental or consequential damages or liability for loss or injury due to negligence, breach of contract or breach of implied terms; in such event, THE LIABILITY OF FORALLDOCTORS.COM TO YOU OR ANY THIRD PARTIES IN ANY CIRCUMSTANCE IS LIMITED TO THE ACTUAL AMOUNT OF DIRECT DAMAGES, EVEN IF DIRECT DAMAGES DO NOT SATISFY A REMEDY.&nbsp; FORALLDOCTORS.COM RESERVES THE RIGHT TO ALL REMEDIES AVAILABLE AT LAW AND IN EQUITY.</span></p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;">&nbsp;</p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">ForAllDoctors.com does not guarantee the availability or accept any responsibility for the suitability, of any of the Site, Communications or its Content in all locations or jurisdictions.&nbsp; It is Your responsibility to be aware of and comply with the laws of the jurisdiction from which You are accessing, using or in any way Communicating with or through the ForAllDoctors.com Site or any of its Content.&nbsp; You agree that You will not access, use or Communicate with or through the ForAllDoctors.com Site or any of its Content in violation of the laws of any such jurisdictions. </span></p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;">&nbsp;</p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">ForAllDoctors.com may, (but is not obligated to) actively monitor the Content, conduct and Communications of any Member or other party for inappropriate Content, conduct or Communications or, undertake editorial control.&nbsp; ForAllDoctors.com Site is intended to be self-monitoring, where all Members and other parties are responsible to self-assess their conduct, Content and Communications and remember to conduct themselves civilly, courteously and professionally at all times. </span></p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;">&nbsp;</p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">You agree that You will not in any way Communicate any Content that is or may be (including but not limited to) defamatory, abusive, profane, threatening, offensive, harassing, libelous, slanderous, harmful, pornographic, degrading, intimidating, hateful, harmful to minors, discriminatory on the basis of race, religion, ethnicity, sexual orientation, gender, age or disability, and/or unlawful or in violation of local, state, federal or international laws, from, on, through or in connection with the ForAllDoctors.com Site.</span></p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;">&nbsp;</p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;"><span style="text-decoration: underline;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">You agree that You will not illegally Communicate any Content protected by copyright, trademark, service mark, trade secret, trade dress, patent or other proprietary laws without the permission of the owner of said intellectual property.&nbsp; By Communicating any such Content, You warrant and represent that You either, own the relevant intellectual property, or that You have obtained correct authorization from the proper owner of that intellectual property for its use.</span></span><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US"> Furthermore, You automatically grant ForAllDoctors.com and its site(s), the worldwide, irrevocable, transferable, royalty free and non-exclusive right, license and sublicense, to Communicate such Content that You have Communicated on, through or in connection with the ForAllDoctors.com Site.&nbsp; You warrant that You have the right and authority to grant such right, license or sublicense to ForAllDoctors.com and its site(s).</span></p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;">&nbsp;</p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">You certify, agree and affirm that You will not falsely represent Your identity, impersonate any other person or entity or Communicate any false or misleading Content whether on, by or through ForAllDoctors.com Site to Members or any other party.</span></p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;">&nbsp;</p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">You agree that You will not Communicate any privileged, confidential, private or personal information of any other person without first obtaining their full written consent. </span></p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;">&nbsp;</p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">You agree that You will not harass or stalk anyone or contact anyone that has asked not to be contacted. </span></p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;">&nbsp;</p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">You agree and affirm that You are at least 18 years of age and/or the age of majority as directly or indirectly imposed on You and applicable to You by international, national, state or local laws and regulations. </span></p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;">&nbsp;</p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">You agree that You will take all precautions when meeting or Communicating with (whether in person or not) any Member or any other party through ForAllDoctors.com Site.&nbsp; You understand and agree that You assume all the risk associated with such meetings (including dating) or communications. </span></p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;">&nbsp;</p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">You agree that You will not Communicate any Content that contains sexual conduct (whether actual or simulated).&nbsp; You should be aware that, pursuant to federal law, any visual depictions that You Communicate on the Website that portrays actual sexually explicit conduct, depictions of the genitals or pubic area, or simulated sexually explicit activity (as such terms are defined in 18 U.S.C. §2256 (2)(A)(i)-(v) and 18 U.S.C. §2257 A), require that You maintain the records required by 18 U.S.C. §2257 and must contain an “18 U.S.C. §2257 Record-Keeping Requirements Compliance Statement.”&nbsp; Your failure to comply with the provisions of 18 U.S.C. §2257 may make You subject to criminal and civil prosecution for the violation of 18 U.S.C. §2257.</span></p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;">&nbsp;</p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">You agree that You will not solicit gambling or engage in any gambling activity; promote or solicit involvement in or support of a political platform, religion, cult or sect.</span></p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">You acknowledge and agree not to disturb the regular function of the ForAllDoctors.com Site or intentionally or with negligent disregard, Communicate or facilitate the Communication of (including without limitation) viruses, worms, Trojan horses, corrupted files, hoaxes or any other material or computer, digital or electronic program that may (including without limitation) disrupt, damage, intercept, expropriate, interrupt, destroy, suspend, delete, manipulate, or in any other way interfere with the computer, digital or electronic hardware, software, system, device, Content, means of Communication, or any other infrastructure and medium of the ForAllDoctors.com Site. You agree and affirm that you will not use spiders, robots, scrapers or any similar data gathering and extraction tool to monitor or copy or collect, any (including without limitation) Member Content, Communications, information, documents or data by whatever means, including and without limitation, manipulating, deactivating, suspending, hacking and accessing any of ForAllDoctors.com’s Site, or its computer, digital or electronic software, hardware, system, device, Content, Communications, means of Communication, or any other infrastructure and medium. </span></p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;">&nbsp;</p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">You acknowledge and agree not use the ForAllDoctors.com Site as a vehicle or means to disturb the regular function, or intentionally or with negligent disregard, Communicate or facilitate the Communication of any (including without limitation) viruses, worms, Trojan horses, corrupted files, hoaxes or any other material or computer, digital or electronic program that may (including without limitation) disrupt, damage, intercept, expropriate, interrupt, destroy, suspend, delete, manipulate, or in any other way interfere with the computer, digital or electronic hardware, software, system, device, Content, Communications, means of Communication, or any other infrastructure and medium of any Member, User or any other third party or entity. You agree and affirm that you will not use the ForAllDoctors.com Site as a vehicle or means to Communicate or facilitate the Communication of spiders, robots, scrapers or any similar data gathering and extraction tool to monitor or copy any Content, information, documents or data of any Member or other party or entity’s, computer, digital or electronic hardware, software, system, device, Content, Communications, means of Communication, or any other infrastructure and medium. </span></p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;">&nbsp;</p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">FORALLDOCTORS.COM DISCLAIMS ANY WARRANTIES AGAINST ANY (INCLUDING WITHOUT LIMITATION) VIRUSES, WORMS, TROJAN HORSES, CORRUPTED FILES, HOAXES OR ANY OTHER MATERIAL OR COMPUTER, DIGITAL OR ELECTRONIC PROGRAM THAT MAY (INCLUDING WITHOUT LIMITATION) DISRUPT, DAMAGE, INTERCEPT, EXPROPRIATE, INTERRUPT, DESTROY, SUSPEND, DELETE, MANIPULATE, OR IN ANY OTHER WAY INTERFERE WITH THE COMPUTER, DIGITAL OR ELECTRONIC HARDWARE, SOFTWARE, SYSTEM, DEVICE, CONTENT, COMMUNICATIONS, MEANS OF COMMUNICATION, OR ANY OTHER INFRASTRUCTURE AND MEDIUM, OF ANY MEMBER OR OTHER PARTY, IN CONNECTION WITH&nbsp; HIS/HER/THEIR/ITS USE OF, MISUSE OF OR ACCESS TO OR COMMUNICATION WITH THE FORALLDOCTORS.COM SITE OR ITS CONTENT. You acknowledge and agree that it is your responsibility to have the most up-to-date (including without limitation) anti-virus and system protection software on your computer, digital or electronic device, medium or means of Communication.&nbsp; You acknowledge and agree that ForAllDoctors.com may (but has no obligation to) filter the Site, Content or Communications for any (including without limitation) viruses, worms, trojan horses, corrupted files, hoaxes or any other computer, digital or electronic program or material. </span></p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;">&nbsp;</p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">You agree and affirm that You will not Yourself or facilitate any other person or entity to (including without limitation) reverse engineer, simulate, imitate, plagiarize, extract, copy or reproduce, create derivative works from the Site, Content or Communications, or in any other manner (including without limitation), manipulate or duplicate, derive any source code, module, metrics, scripts or any other aspect of the ForAllDoctors.com Site. </span></p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;">&nbsp;</p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">You acknowledge and agree that You will not share or permit the use of Your username, login or password with any person or entity and pledge that You will take all necessary measures to keep it secure and confidential.&nbsp; Please be aware that in the event We have any reservation as to the username or login You have selected, We reserve the right to reclaim, disable or remove that username or login name.&nbsp; You acknowledge and agree that You will not create more than one Account with the ForAllDoctors.com Site.&nbsp; You acknowledge and agree that You will not rent, sell, lease, sublicense, assign or transfer Your limited, revocable, non-transferable, non-exclusive license, to access, Communicate or use the ForAllDoctors.com Site or Content.&nbsp; Any attempted transfer or assignment of Your limited, revocable, non-transferable, non-exclusive license or any rights or obligations under this Agreement is in violation of this Agreement and is void. </span></p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;">&nbsp;</p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">You agree that You will not in any way or for any purpose, permit or facilitate any entity or person other than Yourself to access, use, view or Communicate, any Content or Communications of ForAllDoctors.com, its site(s), Members or authorized parties to any person or entity that is not a current Member or authorized party, unless you first obtain the prior specific, written authorization of ForAllDoctors.com by clicking on the “Contact Us” link in the ForAllDoctors.com Site. </span></p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;">&nbsp;</p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">ForAllDoctors.com (either directly or indirectly) owns all proprietary and intellectual property rights of the ForAllDoctors.com Site.&nbsp; ForAllDoctors.com Site, Content, Communications and means of Communication are, the copyright, patent, trademark, trade secrets, trade dress, service mark, proprietary rights and confidential information of ForAllDoctors.com and its site(s)s, protected by United States laws, (including but not limited to) international treaties and conventions.&nbsp; Except as expressly stated in this document, this Agreement does not grant You any proprietary or intellectual property rights in any part of the ForAllDoctors.com Site, Content, Communications or means of Communication.&nbsp; ForAllDoctors.com only provides its Members and authorized parties, a limited, revocable, non-transferable, non-exclusive license to access, participate in and/or use the Site in accordance with the Terms and Conditions of this Agreement.&nbsp; Any rights not expressly granted in the Terms and Conditions of this Agreement are reserved for ForAllDoctors.com.&nbsp; All other trademarks and service marks or copyright materials appearing on any of the ForAllDoctors.com Site that are not owned by ForAllDoctors.com are the property of their respective owners.</span></p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;">&nbsp;</p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">You acknowledge and agree under penalties of perjury, that You will not impersonate any person or entity, provide or maintain inaccurate, false, misleading or outdated information in any manner falsely identifying Yourself to deceive ForAllDoctors.com, its site(s), Members and authorized parties. </span></p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;">&nbsp;</p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">ForAllDoctors.com Site is a PRIVATE Site, restricted to its registered Members and authorized parties only.&nbsp; In an effort to achieve this exclusivity, You agree that You will not permit any access to ForAllDoctors.com Site, by any individual or entity other than yourself, at any time and for any reason, and You agree that You will strictly limit Your use of this Site and any of its Communications and Contents, to Your individual personal use or, to Communicate among other current ForAllDoctors.com Site Members and authorized parties.&nbsp; You must first obtain the prior specific written permission of ForAllDoctors.com if you would like to use or Communicate any of the ForAllDoctors.com Site, Communications or Content with any other person or entity and for any other purpose than that You have agreed to in this Agreement. </span></p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;">&nbsp;</p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">The purpose of this Site is to make available to ForAllDoctors.com Members of that profession a platform where they may access other colleagues, peers and fellow practitioners (in other words, other ForAllDoctors.com Members) from any city, state or jurisdiction, and Communicate ideas, suggestions, wisdom, experiences, knowledge, inquiries and other creative subject matter .&nbsp; All prospective Members represent and guarantee, under penalties of perjury:</span></p>
<ul style="margin-top: 0cm;" type="disc">
<li class="MsoNormalCxSpMiddle" style="margin-bottom: 0.0001pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">that they will not impersonate any other Member, person or entity, or, misrepresent any affiliation with any other Member, person or entity; and</span></li>
<li class="MsoNormalCxSpMiddle" style="margin-bottom: 0.0001pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">that they are or were in fact a legally recognized member of the profession they claim; and</span></li>
<li class="MsoNormalCxSpMiddle" style="margin-bottom: 0.0001pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">that they are legally recognized as being who they identify themselves to be.</span></li>
</ul>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;">&nbsp;</p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">YOU AGREE TO USE GOOD FAITH EFFORTS TO PREVENT, EXPOSING FORALLDOCTORS.COM TO ANY CRITICISM, LIABILITY, CLAIM, DEMAND, CAUSE OF ACTION, LOSS OR DAMAGE OF ANY KIND FOR (INCLUDING BUT NOT LIMITED TO, SPECIAL, DIRECT, INDIRECT, COMPENSATORY, CONSEQUENTIAL, EXEMPLARY, PUNITIVE OR INCIDENTAL DAMAGES OR FOR LOSS OF USE, DATA, PROGRAMS, REPUTATION, GOOD WILL, PROPERTY, INCOME, PROFITS, PROPRIETARY OR CONFIDENTIAL INFORMATION, PRIVACY AND/OR ANY OTHER TANGIBLE, INTANGIBLE OR PECUNIARY LOSS, BUSINESS INTERRUPTION, OR, DAMAGE OR INJURY TO PERSON OR PROPERTY, OR, FOR FAILURE TO MEET ANY DUTY INCLUDING OF GOOD FAITH OR REASONABLE CARE AND/OR PREVENTING NEGLIGENCE, HOWEVER CAUSED AND UNDER ANY THEORY OF LIABILITY, WHETHER IN LAW OR EQUITY), EXPENSES, ATTORNEYS FEES AND COSTS, WHETHER BY YOU OR A THIRD PARTY IN ANY WAY ENABLED THROUGH YOU. Some jurisdictions do not authorize exclusion or limitation of certain warranties or conditions, incidental or consequential damages or liability for loss or injury due to negligence, breach of contract or breach of implied terms; in such event, THE LIABILITY OF FORALLDOCTORS.COM TO YOU OR ANY THIRD PARTY IN ANY CIRCUMSTANCE IS LIMITED TO THE ACTUAL AMOUNT OF DIRECT DAMAGES, EVEN IF DIRECT DAMAGES DO NOT SATISFY A REMEDY.&nbsp; FORALLDOCTORS.COM RESERVES THE RIGHT TO ALL REMEDIES AVAILABLE AT LAW AND IN EQUITY FOR YOUR VIOLATIONS OF THIS AGREEMENT AND FOR YOUR EXPOSING FORALLDOCTORS.COM OR ITS SITE(S) TO CRITICISM OR LIABILITY.</span></p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;">&nbsp;</p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;">&nbsp;</p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">YOU AGREE TO DEFEND, INDEMNIFY AND HOLD FORALLDOCTORS.COM AND ITS SITE(S) HARMLESS FROM ANY LIABILITY, CLAIM, DEMAND, CAUSE OF ACTION, LOSS OR DAMAGE OF ANY KIND FOR (INCLUDING BUT NOT LIMITED TO, SPECIAL, DIRECT, INDIRECT, COMPENSATORY, CONSEQUENTIAL, EXEMPLARY, PUNITIVE OR INCIDENTAL DAMAGES OR FOR LOSS OF USE, DATA, PROGRAMS, REPUTATION, GOOD WILL, PROPERTY, INCOME, PROFITS, PROPRIETARY OR CONFIDENTIAL INFORMATION, PRIVACY AND/OR ANY OTHER TANGIBLE, INTANGIBLE OR PECUNIARY LOSS, BUSINESS INTERRUPTION, OR, DAMAGE OR INJURY TO PERSON OR PROPERTY, OR, FOR FAILURE TO MEET ANY DUTY INCLUDING OF GOOD FAITH OR REASONABLE CARE AND/OR PREVENTING NEGLIGENCE, HOWEVER CAUSED AND UNDER ANY THEORY OF LIABILITY, WHETHER IN LAW OR EQUITY), EXPENSES, ATTORNEYS FEES AND COSTS, WHETHER BY YOU OR A THIRD PARTY,&nbsp; DUE TO OR ARISING OUT OF ANY RELIANCE (WHETHER BY YOU OR ANY THIRD PARTY) UPON, USE OF, INABILITY TO USE, MISUSE, TERMINATION OF USE, OR FOR ANY INTERRUPTION, LIMITATION, DISCONTINUATION, OR ANY OTHER ALTERATION IN, OF THE FORALLDOCTORS.COM SITE, ITS CONTENT OR COMMUNICATIONS. Some jurisdictions do not authorize exclusion or limitation of certain warranties or conditions, incidental or consequential damages or liability for loss or injury due to negligence, breach of contract or breach of implied terms; in such event, THE LIABILITY OF FORALLDOCTORS.COM TO YOU OR ANY THIRD PARTIES IN ANY CIRCUMSTANCE IS LIMITED TO THE ACTUAL AMOUNT OF DIRECT DAMAGES.&nbsp; FORALLDOCTORS.COM RESERVES THE RIGHT TO ALL REMEDIES AVAILABLE AT LAW AND IN EQUITY.</span></p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;">&nbsp;</p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">ForAllDoctors.com does not endorse or accept responsibility, for the Communications, opinions, information or Content of any sort, in any way Communicated on this Site by any Member or any other party.&nbsp; TO THE UTMOST EXTENT PERMITTED BY LAW, FORALLDOCTORS.COM DISCLAIMS ALL WARRANTIES OF SECURITY, TIMELINESS, ACCURACY, INTEGRITY, QUALITY, FUNCTIONALITY, AVAILABILITY, PERFORMANCE, SAFETY OR RELIABILITY OF THE FORALLDOCTORS.COM SITE OR ANY OF THE COMMUNICATIONS, OPINIONS, INFORMATION OR CONTENT OF ANY SORT, IN ANY WAY COMMUNICATED, ANYWHERE ON OR IN CONNECTION WITH THE SITE, WHETHER BY FORALLDOCTORS.COM, ITS MEMBERS OR ANY THIRD PARTY.&nbsp; YOU AGREE THAT UNDER NO CIRCUMSTANCES SHALL FORALLDOCTORS.COM BE LIABLE TO YOU OR ANY THIRD PARTY, FOR ANY CLAIM, DEMAND, CAUSE OF ACTION, LOSS OR DAMAGE OF ANY KIND (INCLUDING BUT NOT LIMITED TO, SPECIAL, DIRECT, INDIRECT, COMPENSATORY, CONSEQUENTIAL, EXEMPLARY, PUNITIVE OR INCIDENTAL DAMAGES OR FOR LOSS OF USE, DATA, PROGRAMS, REPUTATION, GOOD WILL, PROPERTY, INCOME, PROFITS, PROPRIETARY OR CONFIDENTIAL INFORMATION, PRIVACY AND/OR ANY OTHER TANGIBLE, INTANGIBLE OR PECUNIARY LOSS, BUSINESS INTERRUPTION, OR, DAMAGE OR INJURY TO PERSON OR PROPERTY, OR, FOR FAILURE TO MEET ANY DUTY INCLUDING OF GOOD FAITH OR REASONABLE CARE AND/OR NEGLIGENCE, HOWEVER CAUSED AND UNDER ANY THEORY OF LIABILITY, WHETHER IN LAW OR EQUITY), AND FOR EXPENSES, ATTORNEYS FEES AND COSTS, WHETHER MADE OR INCURRED BY YOU OR ANY THIRD PARTY, IN ANY WAY ARISING OUT OF OR IN CONNECTION WITH: THE FORALLDOCTORS.COM SITE OR THIS AGREEMENT, OR THE SECURITY, TIMELINESS, ACCURACY, INTEGRITY, QUALITY, FUNCTIONALITY, AVAILABILITY, PERFORMANCE, SAFETY OR RELIABILITY OF THE FORALLDOCTORS.COM SITE OR ANY COMMUNICATIONS, OPINIONS, INFORMATION OR CONTENT OF ANY SORT, IN ANY&nbsp; WAY COMMUNICATED, ANYWHERE ON OR IN CONNECTION WITH THE SITE, WHETHER BY FORALLDOCTORS.COM, ITS MEMBERS OR ANY PARTY. Some jurisdictions do not authorize exclusion or limitation of certain warranties or conditions, incidental or consequential damages or liability for loss or injury due to negligence, breach of contract or breach of implied terms; in such event, THE LIABILITY OF FORALLDOCTORS.COM TO YOU OR ANY THIRD PARTY IN ANY CIRCUMSTANCE IS LIMITED TO THE ACTUAL AMOUNT OF DIRECT DAMAGES, EVEN IF DIRECT DAMAGES DO NOT SATISFY A REMEDY.&nbsp; FORALLDOCTORS.COM RESERVES THE RIGHT TO ALL REMEDIES AVAILABLE AT LAW AND IN EQUITY.</span></p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;">&nbsp;</p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">YOU AGREE TO DEFEND, INDEMNIFY AND HOLD FORALLDOCTORS.COM HARMLESS FROM ANY CLAIM, DEMAND, CAUSE OF ACTION, LOSS OR DAMAGE OF ANY KIND (INCLUDING BUT NOT LIMITED TO, SPECIAL, DIRECT, INDIRECT, COMPENSATORY, CONSEQUENTIAL, EXEMPLARY, PUNITIVE OR INCIDENTAL DAMAGES OR FOR LOSS OF USE, DATA, PROGRAMS, REPUTATION, GOOD WILL, PROPERTY, INCOME, PROFITS, PROPRIETARY OR CONFIDENTIAL INFORMATION, PRIVACY AND/OR ANY OTHER TANGIBLE, INTANGIBLE OR PECUNIARY LOSS, BUSINESS INTERRUPTION, OR, DAMAGE OR INJURY TO PERSON OR PROPERTY, OR, FOR FAILURE TO MEET ANY DUTY INCLUDING OF GOOD FAITH OR REASONABLE CARE AND/OR NEGLIGENCE, HOWEVER CAUSED AND UNDER ANY THEORY OF LIABILITY, WHETHER IN LAW OR EQUITY), EXPENSES, ATTORNEYS FEES AND COSTS, WHETHER MADE OR INCURRED BY YOU OR ANY THIRD PARTY, DUE TO OR ARISING OUT OF: </span></p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">(1) ANY COMMUNICATION, OPINION, INFORMATION OR CONTENT, IN ANY WAY COMMUNICATED, ANYWHERE ON THE SITE, BY ANY MEMBER OR OTHER THIRD PARTY,&nbsp; SUGGESTING THAT IT CONVEYS THE OPINION, ENDORSEMENT, CONTENT OR COMMUNICATION OF FORALLDOCTORS.COM OR ITS SITE(S)<strong>, OR</strong></span></p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;"><strong><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">(2) </span></strong><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">THE TERMS AND CONDITIONS AND SPIRIT OF THIS AGREEMENT &amp; YOUR BREACH THEREOF, OR</span></p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">(3) IN CONNECTION WITH THIS SITE ITSELF, OR RELATIVE TO YOUR COMMUNICATIONS, CONTENT, ACTIONS, FAILURE TO ACT, USE OR MISUSE OF THE SITE, OR </span></p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">(4) ANY FAILURE OF THE SITE, CONTENT OR COMMUNICATIONS, TO BE: (INCLUDING AND WITHOUT LIMITATION) <strong>SECURE, TIMELY, ACCURATE, COMPLETE, FUNCTIONAL, VIRUS FREE, UNINTERRUPTED, AVAILABLE AS TO OPERATION, CONTENT AND COMMUNICATION, ERROR FREE, CURRENT, INOFFENSIVE, TRUSTWORTHY, DECENT, NON-DISCRIMINATORY, AGREEABLE, SAFE, RELIABLE OR ACCESSIBLE, WHETHER CAUSED OR COMMUNICATED BY FORALLDOCTORS.COM OR ANY OF ITS MEMBERS OR PARTY;</strong></span></p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;"><strong><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">REGARDLESS OF THE LEGAL THEORY ON WHICH THE CLAIM IS BASED AND REGARDLESS OF WHETHER FORALLDOCTORS.COM WAS PREVIOUSLY ADVISED OF THE POSSIBILITY OF SUCH DAMAGE, LOSS OR INJURY OR SHOULD HAVE BEEN AWARE OF THE POTENTIAL FOR SUCH DAMAGE, LOSS OR INJURY OF ANY KIND.</span></strong><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US"> Some jurisdictions do not authorize exclusion or limitation of certain warranties or conditions, incidental or consequential damages or liability for loss or injury due to negligence, breach of contract or breach of implied terms; in such event, THE LIABILITY OF FORALLDOCTORS.COM TO YOU OR ANY THIRD PARTIES IN ANY CIRCUMSTANCE IS LIMITED TO THE ACTUAL AMOUNT OF DIRECT DAMAGES, EVEN IF DIRECT DAMAGES DO NOT SATISFY A REMEDY.&nbsp; FORALLDOCTORS.COM RESERVES THE RIGHT TO ALL REMEDIES AVAILABLE AT LAW AND IN EQUITY.</span></p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;">&nbsp;</p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">You agree that We may (including without limitation) gather: the domain names, internet protocol addresses, pages accessed, metadata, surveys, purchases, e-mails, registrations, e-mail addresses, Member-specific information, information volunteered by Members and other parties to the Site.&nbsp; We may provide third party access to the above mentioned material, information and Site Content that We may maintain, and in the event that ForAllDoctors.com, or its site(s) is sold or acquired, such Member and other party information, Content and Communications will be part of the assets transferred.</span></p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;">&nbsp;</p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">For Your knowledge, the use of cookies by Our Site is for a number of purposes, including without limitation, to: administer Our Site, make ForAllDoctors.com easier to use, improve the quality of Our services, record session information and pages Members or other parties access and, try and avoid the viewing of the same advertisements by the same Member.</span></p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;">&nbsp;</p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">You acknowledge that by accessing ForAllDoctors.com Site, there may be inaccurate, offensive, indecent, misleading or any other direct or indirect potentially disagreeable Content that You may be exposed to.&nbsp; It is the exclusive responsibility of each and every Member and any other party, to exercise professional judgment and conduct due diligence and verify all Content &amp; Communications for (including but not limited to) reliability, accuracy, completeness, error free, virus free, up-to-datedness, inoffensiveness and/or potentially indecent, untrustworthy, false, discriminatory or disagreeable Content of any sort before Communicating it with their fellow ForAllDoctors.com Members or any other party; and conversely, it is the exclusive responsibility of each and every Member and any other party authorized to access the Site, to exercise professional judgment and conduct their own due diligence and verify all Content and Communications for (including but not limited to) reliability, accuracy, completeness, error free, virus free, current, inoffensiveness, decency and/or potentially untrustworthy, false, discriminatory or disagreeable Content of any sort, by whomever Communicated or presented, anywhere on, through or in connection with the Site, before relying upon, implementing, Communicating or in any way sharing same. <strong>Hence, We do not guarantee or assume any liability or responsibility that any Content and Communications, available on, by, through or in connection with ForAllDoctors.com or its site(s) will be (including and without limitation) secure, timely, accurate, complete, functional, virus free, uninterrupted, available as to operation, Content and Communication, error free, current, inoffensive, trustworthy, decent, non-discriminatory, agreeable, safe or reliable, whether made available by ForAllDoctors.com or by any of its Members or any other party, regardless of whether ForAllDoctors.com was previously advised of or should have been aware of any such shortcomings.</strong></span></p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;">&nbsp;</p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US"> <strong>IF YOU FEEL THREATENED OR BELIEVE SOMEONE ELSE TO BE IN DANGER, YOU SHOULD CONTACT YOUR LOCAL LAW ENFORCEMENT AGENCY OR 911 (EMERGENCY PHONE NUMBER) IMMEDIATELY.&nbsp; IF YOU THINK YOU MAY HAVE A MEDICAL EMERGENCY, YOU SHOULD CALL YOUR DOCTOR OR 911 (EMERGENCY PHONE NUMBER) OR GO TO THE NEAREST HOSPITAL IMMEDIATELY.</strong></span></p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;">&nbsp;</p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">You agree to not Communicate using misleading: e-mail addresses, titles, headers, identifiers including without limitation any repeated duplicate or irrelevant Content that may in any way hinder the ordinary flow of discourse among ForAllDoctors.com Members or other party, on, through, or in connection with ForAllDoctors.com Site.</span></p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;">&nbsp;</p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">Except with the express prior written permission of ForAllDoctors.com, Members or other party are prohibited from engaging the services of Posting Agents and conversely, Posting Agents are prohibited from accessing the Site to post or to cause the posting of Content for their own purposes or on behalf of Members or any other party.&nbsp; Members are prohibited from using any form of computer program or automated device that causes the submission of bulk or automatic postings in previously designated intervals.</span></p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;">&nbsp;</p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">TO THE EXTENT PERMITTED BY LAW, FORALLDOCTORS.COM EXPRESSLY DISCLAIMS ANY AND ALL EXPRESS AND IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT OF PROPRIETARY AND INTELLECTUAL PROPERTY RIGHTS.&nbsp; FORALLDOCTORS.COM SITE IS PROVIDED ON AN “AS IS,” “WITH ALL FAULTS,” AND “AS AVAILABLE” BASIS ONLY.&nbsp; IN NO EVENT WILL FORALLDOCTORS.COM WARRANT OR BE LIABLE TO ANY MEMBER OR PARTY FOR CLAIM, DEMAND, CAUSE OF ACTION, LOSS OR DAMAGE OF ANY KIND (INCLUDING BUT NOT LIMITED TO, SPECIAL, DIRECT, INDIRECT, COMPENSATORY, CONSEQUENTIAL, EXEMPLARY, PUNITIVE OR INCIDENTAL DAMAGES OR FOR LOSS OF USE, DATA, PROGRAMS, REPUTATION, GOOD WILL, PROPERTY, INCOME, PROFITS, PROPRIETARY OR CONFIDENTIAL INFORMATION, PRIVACY AND/OR ANY OTHER TANGIBLE, INTANGIBLE OR PECUNIARY LOSS, BUSINESS INTERRUPTION, OR, DAMAGE OR INJURY TO PERSON OR PROPERTY, OR, FOR FAILURE TO MEET ANY DUTY INCLUDING OF GOOD FAITH OR REASONABLE CARE AND/OR NEGLIGENCE, HOWEVER CAUSED AND UNDER ANY THEORY OF LIABILITY, WHETHER IN LAW OR EQUITY), EXPENSES, ATTORNEYS FEES AND COSTS, WHETHER BY YOU OR A THIRD PARTY, ARISING OUT OF OR IN CONNECTION WITH FORALLDOCTORS.COM, ITS SITE(S), ANY OF ITS MEMBERS OR ANY OTHER PARTY, REGARDLESS OF THE LEGAL THEORY ON WHICH THE CLAIM IS BASED, EVEN IF FORALLDOCTORS.COM WAS PREVIOUSLY ADVISED OF THE POSSIBILITY OF SUCH SHORTCOMINGS OR DAMAGES OR SHOULD HAVE BEEN AWARE OF THE POTENTIAL FOR SUCH SHORTCOMINGS OR DAMAGES. Some jurisdictions do not authorize exclusion or limitation of certain warranties or conditions, incidental or consequential damages or liability for loss or injury due to negligence, breach of contract or breach of implied terms; in such event, THE LIABILITY OF FORALLDOCTORS.COM TO YOU OR ANY THIRD PARTIES IN ANY CIRCUMSTANCE IS LIMITED TO THE ACTUAL AMOUNT OF DIRECT DAMAGES, EVEN IF DIRECT DAMAGES DO NOT SATISFY A REMEDY.&nbsp; FORALLDOCTORS.COM RESERVES THE RIGHT TO ALL REMEDIES AVAILABLE AT LAW AND IN EQUITY.</span></p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;">&nbsp;</p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">You acknowledge and agree that ForAllDoctors.com does not warranty that any defects on its site(s) whether they should be known, are made known or were known to ForAllDoctors.com, will be addressed or corrected.</span></p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;">&nbsp;</p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL FORALLDOCTORS.COM BE LIABLE FOR ANY CLAIM, DEMAND, CAUSE OF ACTION, LOSS OR DAMAGE OF ANY KIND (INCLUDING BUT NOT LIMITED TO, SPECIAL, DIRECT, INDIRECT, COMPENSATORY, CONSEQUENTIAL, EXEMPLARY, PUNITIVE OR INCIDENTAL DAMAGES OR FOR LOSS OF USE, DATA, PROGRAMS, REPUTATION, GOOD WILL, PROPERTY, INCOME, PROFITS AND/OR ANY OTHER TANGIBLE,&nbsp; INTANGIBLE OR PECUNIARY LOSS, BUSINESS INTERRUPTION, OR, DAMAGE OR INJURY TO PERSON OR PROPERTY, OR, FOR FAILURE TO MEET ANY DUTY INCLUDING OF GOOD FAITH OR REASONABLE CARE, OR FOR NEGLIGENCE, HOWEVER CAUSED AND UNDER ANY THEORY OF LIABILITY, WHETHER IN LAW OR EQUITY), EXPENSES, ATTORNEYS FEES AND COSTS, ARISING OUT OF OR IN ANY WAY RELATED TO THE USE OF, MISUSE OF OR INABILITY TO USE THE FORALLDOCTORS.COM SITE OR ANY PART OR COMPONENT THEREOF OR RELATED SERVICES, OR OTHERWISE IN CONNECTION WITH THE TERMS AND CONDITIONS OF THIS AGREEMENT, MISREPRESENTATION, STRICT LIABILITY, BREACH OF WARRANTY OF FORALLDOCTORS.COM AND EVEN IF FORALLDOCTORS.COM WAS PREVIOUSLY ADVISED OF THE POSSIBILITY OF SUCH DAMAGES OR SHORTCOMINGS OR SHOULD HAVE BEEN AWARE OF THE POTENTIAL FOR SUCH DAMAGES OR SHORTCOMINGS, AND NOTWITHSTANDING ANY FAILURE OF THE ESSENTIAL PURPOSE OF THIS AGREEMENT OR ANY REMEDY. Some jurisdictions do not authorize exclusion or limitation of certain warranties or conditions, incidental or consequential damages or liability for loss or injury due to negligence, breach of contract or breach of implied terms; in such event, THE LIABILITY OF FORALLDOCTORS.COM TO YOU OR ANY THIRD PARTIES IN ANY CIRCUMSTANCE IS LIMITED TO THE ACTUAL AMOUNT OF DIRECT DAMAGES, EVEN IF DIRECT DAMAGES DO NOT SATISFY A REMEDY.&nbsp; FORALLDOCTORS.COM RESERVES THE RIGHT TO ALL REMEDIES AVAILABLE AT LAW AND IN EQUITY.</span></p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;">&nbsp;</p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">Each Member or other authorized party, of ForAllDoctors.com Site may be offered an exclusive Web page(s), that may be accessible by the general public, where they may publish their own information, biography, bibliography, profile, data, services, products, and any other Content related to their profession that is not defamatory, abusive, profane, threatening, offensive, harassing, libelous, slanderous, harmful, pornographic, embarrassing, degrading, intimidating, hateful, harmful to minors, discriminatory on the basis of race, religion, ethnicity, sexual orientation, gender, age or disability, and/or in anyway unlawful or in violation of local, state, federal or international laws. You agree that You will not: falsely represent Your identity, impersonate any other person or entity, or infringe on the intellectual property rights of others.&nbsp; You agree to audit and verify that any and all Content You make available on the Web page(s) does not in any way imply that ForAllDoctors.com (including without limitation) promotes, endorses, guarantees, certifies or, in any way warranties the Content made available on the Web page(s).&nbsp; Each Member and user agrees that they shall not under any circumstances create links or make available any Content and Communications of the Site that is intended for and limited to the current Members and other parties of the Site only, and as further set forth in the terms and conditions of this Agreement.</span></p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;">&nbsp;</p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">You agree that ForAllDoctors.com may (but is not obligated to), review, modify, remove, filter, audit, censor, restrict or refuse any Content or entry of any sort in any form, that may be (including without limitation) defamatory, abusive, profane, threatening, offensive, harassing, libelous, slanderous, harmful, pornographic, embarrassing, degrading, intimidating, hateful, harmful to minors, discriminatory on the basis of race, religion, ethnicity, sexual orientation, gender, age or disability, and/or unlawful or in violation of local, state, federal or international laws, in any manner Communicated on, through or in connection with the ForAllDoctors.com Site.</span></p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;">&nbsp;</p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;"><strong><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">You agree that ForAllDoctors.com retains the right to seek to the maximum extent permitted by applicable law (including without limitation), liability for any claim, demand, cause of action, loss or damage of any kind (including but not limited to, preliminary or permanent injunction, or, special, direct, indirect, compensatory, consequential, exemplary, punitive or incidental damages or for loss of use, data, programs, reputation, good will, property, income, profits, proprietary or confidential information, privacy and/or any other tangible, intangible or pecuniary loss, business interruption, or, damage or injury to person or property, or, for failure to meet any duty including of good faith or reasonable care and/or negligence, however caused and under any theory of liability, whether in law or equity), expenses, attorneys fees and costs, due to or arising out of Your actions or inactions or that of any other party acting at Your direction, on Your behalf or associated with You, in breaching the Terms, Conditions and the spirit of this Agreement.</span></strong><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US"> Some jurisdictions do not authorize exclusion or limitation of certain warranties or conditions, incidental or consequential damages or liability for loss or injury due to negligence, breach of contract or breach of implied terms; in such event, THE LIABILITY OF FORALLDOCTORS.COM TO YOU OR ANY THIRD PARTIES IN ANY CIRCUMSTANCE IS LIMITED TO THE ACTUAL AMOUNT OF DIRECT DAMAGES, EVEN IF DIRECT DAMAGES DO NOT SATISFY A REMEDY.&nbsp; FORALLDOCTORS.COM RESERVES THE RIGHT TO ALL REMEDIES AVAILABLE AT LAW AND IN EQUITY.</span></p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;">&nbsp;</p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">YOU ACKNOWLEDGE AND AGREE THAT REGARDLESS OF ANY STATUTE, LAW, CODE, REGULATION OR LEGAL PRECEDENCE TO THE CONTRARY, ANY CLAIM, DEMAND, CAUSE OF ACTION FOR LOSS OR DAMAGE OF ANY KIND (INCLUDING BUT NOT LIMITED TO, SPECIAL, DIRECT, INDIRECT, COMPENSATORY, CONSEQUENTIAL, EXEMPLARY, PUNITIVE OR INCIDENTAL DAMAGES OR FOR LOSS OF USE, DATA, PROGRAMS, REPUTATION, GOOD WILL, PROPERTY, INCOME, PROFITS PROPRIETARY OR CONFIDENTIAL INFORMATION, PRIVACY, AND/OR ANY OTHER TANGIBLE,&nbsp; INTANGIBLE OR PECUNIARY LOSS, BUSINESS INTERRUPTION, OR, DAMAGE OR INJURY TO PERSON OR PROPERTY, OR, FOR FAILURE TO MEET ANY DUTY INCLUDING OF GOOD FAITH OR REASONABLE CARE, OR FOR NEGLIGENCE, HOWEVER CAUSED AND UNDER ANY THEORY OF LIABILITY, WHETHER IN LAW OR EQUITY), EXPENSES, ATTORNEYS FEES AND COSTS (INCLUDING EXPENSES, SETTLEMENT COSTS AND REASONABLE ATTORNEYS’ FEES ARISING OUT OF A THIRD PARTY CLAIM), ARISING OUT OF OR IN ANY WAY RELATED TO THE USE OF, MISUSE OF OR INABILITY TO USE THE FORALLDOCTORS.COM SITE OR ANY COMPONENT THEREOF OR RELATED SERVICES, OR OTHERWISE IN CONNECTION WITH THE TERMS AND CONDITIONS OF THIS AGREEMENT, MISREPRESENTATION, STRICT LIABILITY OR BREACH OF WARRANTY OF FORALLDOCTORS.COM AND EVEN IF FORALLDOCTORS.COM WAS PREVIOUSLY ADVISED OF THE POSSIBILITY OF SUCH DAMAGES OR SHORTCOMINGS OR SHOULD HAVE BEEN AWARE OF THE POTENTIAL FOR SUCH DAMAGES OR SHORTCOMINGS, AND NOTWITHSTANDING ANY FAILURE OF THE ESSENTIAL PURPOSE OF THIS AGREEMENT OR ANY REMEDY,&nbsp; <strong>SHALL BE FILED NO LATER THAN FIFTEEN (15) DAYS AFTER SUCH CLAIM, DEMAND OR CAUSE OF ACTION AROSE OR BE FOREVER BARRED. </strong>Some jurisdictions do not authorize exclusion or limitation of certain warranties or conditions, incidental or consequential damages or liability for loss or injury due to negligence, breach of contract or breach of implied terms; in such event, THE LIABILITY OF FORALLDOCTORS.COM TO YOU OR ANY THIRD PARTIES IN ANY CIRCUMSTANCE IS LIMITED TO THE ACTUAL AMOUNT OF DIRECT DAMAGES, EVEN IF DIRECT DAMAGES DO NOT SATISFY A REMEDY.&nbsp; FORALLDOCTORS.COM RESERVES THE RIGHT TO ALL REMEDIES AVAILABLE AT LAW AND IN EQUITY.</span></p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;">&nbsp;</p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;">&nbsp;</p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">You acknowledge and agree that ForAllDoctors.com may at any time set limits or amend the permissible quantity of, Communications and Content storage it has available for each Member or other party.</span></p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;">&nbsp;</p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">You agree that You shall not remove, modify or in any manner make illegible, any (including without limitation) notice, disclaimer or reference that may be affixed to any part of the Site, its Content or Communications.&nbsp; You agree not to use any copyright, trade mark, trade name, service mark, domain name, logo or brand name of ForAllDoctors.com as part of or within Your trademark, in a manner that may cause confusion or in a manner that implies any association, connection or endorsement by ForAllDoctors.com or is disparaging of ForAllDoctors.com, without first submitting Your request to ForAllDoctors.com in writing, in a timely manner, and obtaining the specific written consent of ForAllDoctors.com first, before making such use.</span></p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;">&nbsp;</p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">ForAllDoctors.com may at any time, without cause or notice to you, terminate this Agreement, however, the Terms, Conditions, provisions, notices, disclaimers, obligations, liabilities and rights under this Agreement that were in force during Your Membership with ForAllDoctors.com, shall be enforceable according to the Terms and Conditions of this Agreement for the duration of time specified as may be applicable, and those which continue to apply indefinitely shall remain unaffected.</span></p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;">&nbsp;</p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">You agree that ForAllDoctors.com may Communicate with You regarding notices, updates, and any other relevant information and Content either by regular mail, phone, e-mail, (including without limitation) or through the ForAllDoctors.com Site.</span></p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;">&nbsp;</p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">You acknowledge and agree that the terms and conditions of this Agreement and all its amendments shall be governed by the laws of the British Virgin Islands without regard to any conflict of laws provisions.&nbsp; You agree to submit to the personal jurisdiction of British Virgin Islands and that any dispute, cause of action or legal matter arising out of or relating to the terms and condition of this Agreement and its amendments shall be tried, litigated and/or resolved exclusively in the British Virgin Islands state and/or federal courts located in the appropriate County of British Virgin Islands, EU. </span></p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;">&nbsp;</p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">Should any court of competent jurisdiction declare any Term or Condition of this Agreement void or unenforceable, such term or condition will be changed or interpreted so as to best accomplish the objectives of the original Term or Condition to the fullest extent allowed by law and the remainder of this Agreement shall remain in full force and effect.</span></p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;">&nbsp;</p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">This Agreement is not for any third party beneficiary.&nbsp; We may assign, transfer, or otherwise allocate this Agreement, in whole or in part, at any time without notice.&nbsp; You may not assign this Agreement or any rights to use the Site.</span></p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;">&nbsp;</p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">This Agreement and all documents referenced herein constitute the entire Agreement and supersede any prior or contemporaneous Agreements. </span></p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;"><strong><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">DEFINITIONS:</span></strong></p>
<p class="MsoNormal" style="margin-bottom: 0.0001pt;">&nbsp;</p>
<p class="MsoNormalCxSpMiddle" style="margin: 0cm 0cm 0.0001pt 72pt; text-indent: -18pt;"><!-- [if !supportLists]--><span style="font-size: 12.0pt; font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol;" lang="EN-US">· </span><!--[endif]--><strong><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">Site/ForAllDoctors.com Site/ForAllDoctors.com</span></strong><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">:&nbsp; Includes Our URL, websites, IP addresses, servers, databases, web pages, discussion boards, bulletin boards, discussion forums, listings, directories, postings, advertisings, classifieds, catalogues, rosters, news groups, message boards, blogs, chat rooms, message boxes, tagboards, imageboards, e-mail addresses, domain names, domain addresses, structures, modules, metrics, scripts, coding, technology, programs, designs, architecture, frame works, appearance, layouts, interfaces, audios, images, data, metadata, specifications, icons, illustrations, photographs, software, texts, hypertexts, hyperlinks, links, video clips, animations, graphics, multimedia, logos, marks, emblems, scripts, organization, documents, applications, languages (including programming, markup and style sheets), products, services and, including without limitation, all other such similar Content (as defined herein) or means and modules regardless of whether in electronic or digital format or not.</span></p>
<p class="MsoNormalCxSpMiddle" style="margin: 0cm 0cm 0.0001pt 72pt;">&nbsp;</p>
<p class="MsoNormalCxSpMiddle" style="margin: 0cm 0cm 0.0001pt 72pt; text-indent: -18pt;"><!-- [if !supportLists]--><span style="font-size: 12.0pt; font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol;" lang="EN-US">· </span><!--[endif]--><strong><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">Agreement/Terms and Conditions</span></strong><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">:&nbsp; Includes, obligations, disclaimers, warnings, waivers, exceptions, exemptions, provisions, policies, notices, notes, guidelines, recommendations, acknowledgements, consents, suggestions, comments, provisions, stipulations, requirements, rules, principles, responsibilities, rights, interests, warranties, guarantees and other such similar content of this Agreement.</span></p>
<p class="MsoNormalCxSpMiddle" style="margin-bottom: 0.0001pt;">&nbsp;</p>
<p class="MsoNormalCxSpMiddle" style="margin: 0cm 0cm 0.0001pt 72pt; text-indent: -18pt;"><!-- [if !supportLists]--><span style="font-size: 12.0pt; font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol;" lang="EN-US">· </span><!--[endif]--><strong><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">Member/You/Your</span></strong><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">:&nbsp; Includes registered professional authorized by ForAllDoctors.com to access the ForAllDoctors.com Site, advertiser, sponsor, supporter, endorser, promoter, registered user or subscriber, person or entity authorized to access the ForAllDoctors.com Site for predefined purposes set forth by ForAllDoctors.com as well as, any Agency or Broker employed by Advertiser to engage the services of ForAllDoctors.com, and any other such similar entities and individuals.</span></p>
<p class="MsoNormalCxSpMiddle" style="margin-bottom: 0.0001pt;">&nbsp;</p>
<p class="MsoNormalCxSpMiddle" style="margin: 0cm 0cm 0.0001pt 72pt; text-indent: -18pt;"><!-- [if !supportLists]--><span style="font-size: 12.0pt; font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol;" lang="EN-US">· </span><!--[endif]--><strong><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">ForAllDoctors.com/We/Our/Us</span></strong><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">:&nbsp; Includes <img src="/images/ccorp.png" alt="" height="13px"> and its partners, affiliates, subsidiaries, successors, officers, directors, executives, representatives, administrators, agents, associates, employees, staff, service providers, contractors, suppliers and other such similar entities and individuals.</span></p>
<p class="MsoNormalCxSpMiddle" style="margin-bottom: 0.0001pt;">&nbsp;</p>
<p class="MsoNormalCxSpMiddle" style="margin: 0cm 0cm 0.0001pt 72pt; text-indent: -18pt;"><!-- [if !supportLists]--><span style="font-size: 12.0pt; font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol;" lang="EN-US">· </span><!--[endif]--><strong><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">Content</span></strong><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">:&nbsp; Includes, data, metadata, communications, correspondences, e-mails, classifieds, forums, personals, listings, messages, information, opinions, suggestions, documents, letters, declarations, material, offers, advertisings, promotions, statements, domain names, registrations, texts, scripts, records, facts, figures, writings, symbols, and all such similar items regardless of whether in digital or electronic form or not, URLs, websites, servers, IP addresses, databases, web pages, discussion boards, bulletin boards, discussion forums, listings, directories, postings, advertisings, catalogues, rosters, news groups, message boards, blogs, chat rooms, message boxes, tagboards, imageboards, structures, modules, metrics, coding, technology, programs, designs, architecture, frame works, appearance, layouts, interfaces, audios, images, look &amp; feel, expression, colors, color combination, compilation, specifications, icons, illustrations, photographs, software, hypertexts, hyperlinks, links, video clips, animations, graphics, multimedia, logos, marks, emblems, scripts, organization, applications, languages (including programming, markup and style sheets), products, services and, including without limitation, all other such similar Content (as defined herein), identifiable section, or means and modules,&nbsp; regardless of whether in electronic or digital format or not.</span></p>
<p class="MsoNormalCxSpMiddle" style="margin-bottom: 0.0001pt;">&nbsp;</p>
<p class="MsoNormalCxSpMiddle" style="margin: 0cm 0cm 0.0001pt 72pt; text-indent: -18pt;"><!-- [if !supportLists]--><span style="font-size: 12.0pt; font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol;" lang="EN-US">· </span><!--[endif]--><strong><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">Communicate/Communication/Communicating/Communicated</span></strong><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman';" lang="EN-US">:&nbsp; Include, e-mail, correspond, contact, display, publish, post, distribute, broadcast, transmit, call, convey, upload, download, send, declare, produce, reproduce, duplicate, disseminate, suggest, imply, advocate, link, hyperlink, print, relicense, sell, advise, offer, write, relay, say, inform, direct, offer, advertise, circulate, make available, make visible, present, exhibit, demonstrate, show, illustrate and other such similar means regardless of whether in digital or electronic form or not.</span></p>
<p class="MsoListParagraphCxSpFirst" style="margin-left: 72.0pt; mso-add-space: auto; text-indent: -18.0pt; mso-list: l3 level1 lfo3;"><!-- [if !supportLists]--><span style="font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol;" lang="EN-US">· </span><!--[endif]--><strong><span lang="EN-US">Account</span></strong><span lang="EN-US">:&nbsp; Consist of a Member’s or other authorized party’s username or login and password or pass code, a means of accessing the ForAllDoctors.com Site.</span></p>
</div> 	</div>
            <hr>
       </div>
    </div>
    <!--container end-->